version: '3.8'

services:
  omada-controller:
    image: mbentley/omada-controller:6.2.14.11-openj9@sha256:53ac3e6606194f0309f1f5477d4e936bdc9937edd5166b29cca7336ab9bad01f
    container_name: omada
    restart: unless-stopped
    ports:
      - "8088:8088/tcp"
      - "8043:8043/tcp"
      - "29810:29810/udp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
    volumes:
      - omada_data:/opt/tplink/EAPController/data
    env_file:
      - /opt/secrets/omada/omada.env

volumes:
  omada_data:
