version: '3.8'

services:
  omada-controller:
    image: mbentley/omada-controller:6.3.0.45-openj9@sha256:f26f871e48454d948691b4fb339b7fada2b3f3f586a2391ea74bba007d5c7148
    container_name: omada
    restart: unless-stopped
    ports:
      - "8088:8088/tcp"
      - "8043:8043/tcp"
      - "29810:29810/udp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
    volumes:
      - omada_data:/opt/tplink/EAPController/data
    env_file:
      - /opt/secrets/omada/omada.env

volumes:
  omada_data:
