version: '3.8'

services:
  technitium:
    image: technitium/dns-server:15.1.0@sha256:9f26522bf1d484e85f7753a324876c5cb4a3ab6deab5a753997007de98fda300
    container_name: technitium
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:5380/tcp"
      - "53443:53443/tcp"
    volumes:
      - technitium_data:/etc/dns
    env_file:
      - /opt/secrets/technitium/technitium.env
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

volumes:
  technitium_data:
