version: '3.8'

services:
  technitium:
    image: technitium/dns-server:15.0.1@sha256:7d8dad8fd8571b04989e26e6dbab8aa0004aa0cf333dc870a3f34acda750f4e9
    container_name: technitium
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:5380/tcp"
      - "53443:53443/tcp"
    volumes:
      - technitium_data:/etc/dns
    env_file:
      - /opt/secrets/technitium/technitium.env
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

volumes:
  technitium_data:
