apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-config-secret
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: democratic-csi-iscsi-custom-driver-config
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Do not simplify extentCommentTemplate: triple templating escape for Helm/Argo/ESO -> outputs literal
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            allowInsecure: false
            apiKey: '{{ `{{ .TRUENAS_API_KEY }}` }}'
            apiVersion: 2
            host: '{{ `{{ .TRUENAS_HOST }}` }}'
            port: 443
            protocol: https
            username: root
          instance_id: null
          iscsi:
            extentAvailThreshold: 0
            extentBlocksize: 512
            extentCommentTemplate: '{{ `{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/namespace] {{ "}}" }}/{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/name] {{ "}}" }}` }}'
            extentDisablePhysicalBlocksize: true
            extentInsecureTpc: true
            extentRpm: SSD
            extentXenCompat: true
            interface: null
            namePrefix: apps-
            nameSuffix: null
            targetGroups:
            - targetGroupAuthGroup: 1
              targetGroupAuthType: CHAP
              targetGroupInitiatorGroup: 1
              targetGroupPortalGroup: 1
            targetPortal: "{{ `{{ .TRUENAS_ISCSI_PORTAL }}` }}"
            targetPortals: []
          zfs:
            cli:
              paths:
                chroot: /usr/sbin/chroot
                sudo: /usr/bin/sudo
                zfs: /usr/sbin/zfs
                zpool: /usr/sbin/zpool
            datasetParentName: data/Apps
            detachedSnapshotsDatasetParentName: data/Snapshots
            zvolBlocksize: null
            zvolCompression: null
            zvolDedup: null
            zvolEnableReservation: false
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: apps/democratic-csi/truenas
        property: api_key
    - secretKey: TRUENAS_HOST
      remoteRef:
        key: apps/democratic-csi/truenas
        property: host
    - secretKey: TRUENAS_ISCSI_PORTAL
      remoteRef:
        key: apps/democratic-csi/truenas
        property: iscsi_portal
