---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-node-stage-secret
  namespace: democratic-csi
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # node-stage-secret-truenas-iscsi-nas-democratic-csi-iscsi-nas
    name: node-stage-secret-truenas-{{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: node-db.node.session.auth.authmethod
      remoteRef:
        key: apps/democratic-csi/truenas
        property: iscsi_auth_method
    - secretKey: node-db.node.session.auth.password
      remoteRef:
        key: apps/democratic-csi/truenas
        property: iscsi_password
    - secretKey: node-db.node.session.auth.username
      remoteRef:
        key: apps/democratic-csi/truenas
        property: iscsi_username
