apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://minicloudlabs.github.io/helm-charts
      chart: gatus
      targetRevision: 3.4.1
      helm:
        valueFiles:
          - $values/kubernetes/overrides/gatus/values.yaml
        values: |
          config:
            ui:
              link: https://status.{{ .Values.domain }}/
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
