all:
  children:
    always_on:
      hosts:
        srv-26:
          ansible_host: 10.222.0.186
        srv-27:
          ansible_host: 10.222.0.187
        srv-28:
          ansible_host: 10.222.0.188
