version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:v1.96.5@sha256:dbeff02d2337344b351afac203427218c4d0a06c43fc10a865184063498472a6
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - tailscale_data:/var/lib/tailscale
    env_file:
      - /opt/secrets/tailscale/tailscale.env

  gatus:
    image: twinproduction/gatus:v5.35.0@sha256:21609f31be8c4e680ce3004b24276305666239c99aff58391503f3fb6142f39d
    container_name: gatus
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./gatus-config.yaml:/etc/gatus/config.yaml
    env_file:
      - /opt/secrets/gatus/gatus.env

  ntfy:
    image: binwiederhier/ntfy:v2.22.0@sha256:d8b3408c75d5ae78e03339af6103e7e6195e56573eea6f1ad34bb4dc4f44f340
    container_name: ntfy
    restart: unless-stopped
    ports:
      - "8090:80/tcp"
    volumes:
      - ntfy_data:/var/lib/ntfy
    env_file:
      - /opt/secrets/ntfy/ntfy.env

volumes:
  tailscale_data:
  ntfy_data:
