version: '3.8'

services:
  technitium:
    image: technitium/dns-server:latest
    container_name: technitium
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:5380/tcp"
    volumes:
      - technitium_data:/etc/technitium
    env_file:
      - /opt/secrets/technitium/technitium.env

volumes:
  technitium_data:
