apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itop
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      targetRevision: 4.1.2
      helm:
        valueFiles:
          - $values/kubernetes/overrides/itop/values.yaml
        parameters:
          - name: "controllers.main.containers.main.image.repository"
            value: '{{ include "apps.itop.image" . }}'
          - name: "ingress.main.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
            value: '{{ include "apps.itop.hostname" . }}.'
          - name: "ingress.main.hosts[0].host"
            value: '{{ include "apps.itop.hostname" . }}'
          - name: "ingress.main.tls[0].hosts[0]"
            value: '{{ include "apps.itop.hostname" . }}'
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: itop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
