apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://8gears.container-registry.com/library/n8n
      path: "."
      targetRevision: 2.0.1
      helm:
        valueFiles:
          - $values/kubernetes/overrides/n8n/values.yaml
        parameters:
          - name: "ingress.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
            value: '{{ include "apps.n8n.hostname" . }}.'
          - name: "ingress.hosts[0].host"
            value: '{{ include "apps.n8n.hostname" . }}'
          - name: "ingress.tls[0].hosts[0]"
            value: '{{ include "apps.n8n.hostname" . }}'
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
