# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.1.2/charts/library/common/values.schema.json
defaultPodOptions:
  enableServiceLinks: false
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault

controllers:
  main:
    type: statefulset
    replicas: 1
    statefulset:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
    initContainers:
      config-init:
        image:
          repository: docker.io/mikefarah/yq
          tag: "4.44.3@sha256:5b3d851bf28b04ef902fee86305f4dd7e063919c1cafedab2042adb16221c025"
        command:
          - /bin/sh
          - -c
        args:
          - |
            echo "Initialzing configuration.yaml with MQTT credentials from ExternalSecret"

            if [ ! -f /app/data/configuration.yaml ]; then
              echo "Setting up configuration.yaml for the first time"
              cp /base-config/configuration.yaml /app/data/configuration.yaml
            fi
            MQTT_USER=$(cat /creds/MQTT_USERNAME)
            MQTT_PASS=$(cat /creds/MQTT_PASSWORD)
            export MQTT_USER MQTT_PASS

            echo "Inputting MQTT credentials into configuration.yaml"
            yq '.mqtt.user = env(MQTT_USER) | .mqtt.password = env(MQTT_PASS)' \
              /app/data/configuration.yaml > /tmp/configuration.yaml

            echo "Replacing configuration.yaml with new version containing MQTT credentials"
            rm /app/data/configuration.yaml
            mv /tmp/configuration.yaml /app/data/configuration.yaml

            echo "Configuration after init container:"
            cat /app/data/configuration.yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
    containers:
      main:
        image:
          repository: docker.io/koenkk/zigbee2mqtt
          tag: 2.10.1@sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80
        ports:
          - containerPort: 8081
            name: frontend
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 40m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 500Mi
            squat.ai/cp210x: "1"
        probes:
          readiness:
            enabled: false
            custom: false
            type: TCP

ingress:
  main:
    enabled: false

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

rawResources:
  base-config:
    apiVersion: v1
    kind: ConfigMap
    spec:
      metadata:
        name: zigbee2mqtt-base-config
      data:
        configuration.yaml: |
          version: 4
          serial:
            port: /dev/ttyUSB0
            adapter: ember
            baudrate: 115200
            rtscts: false
          advanced:
            log_level: info
            channel: 25
            network_key:
              - 86
              - 183
              - 125
              - 48
              - 129
              - 119
              - 191
              - 48
              - 141
              - 101
              - 209
              - 197
              - 66
              - 82
              - 142
              - 229
            pan_id: 49349
            ext_pan_id:
              - 180
              - 64
              - 2
              - 50
              - 92
              - 41
              - 14
              - 46
          frontend:
            enabled: true
            package: zigbee2mqtt-windfront
            port: 8081
          homeassistant:
            enabled: true
            experimental_event_entities: true
            legacy_action_sensor: true
          permit_join: true
          mqtt:
            base_topic: zigbee2mqtt
            server: "mqtt://home-assistant-mqtt:8883"
            user: ""
            password: ""
          device_options:
            legacy: false
  mqtt-creds:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    spec:
      metadata:
        name: zigbee2mqtt-mqtt-creds
      spec:
        refreshInterval: 1h
        secretStoreRef:
          name: vault-backend
          kind: ClusterSecretStore
        target:
          name: zigbee2mqtt-mqtt-creds
          creationPolicy: Owner
        data:
          - secretKey: MQTT_USERNAME
            remoteRef:
              key: apps/home-assistant/mqtt
              property: username
          - secretKey: MQTT_PASSWORD
            remoteRef:
              key: apps/home-assistant/mqtt
              property: password

  netpol-allow-zigbee2mqtt:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    spec:
      metadata:
        name: allow-zigbee2mqtt
      spec:
        podSelector:
          matchLabels:
            app.kubernetes.io/name: home-assistant-zigbee2mqtt
        policyTypes:
          - Egress
        egress:
          - to:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/name: home-assistant-mqtt
            ports:
              - port: 1883
                protocol: TCP

persistence:
  data:
    existingClaim: pvc-zigbee2mqtt-data
    advancedMounts:
      main:
        config-init:
          - path: /app/data
        main:
          - path: /app/data
  base-config:
    type: configMap
    name: zigbee2mqtt-base-config
    advancedMounts:
      main:
        config-init:
          - path: /base-config
  mqtt-creds:
    type: secret
    name: zigbee2mqtt-mqtt-creds
    advancedMounts:
      main:
        config-init:
          - path: /creds
