apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns-resolver
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      targetRevision: 4.1.2
      helm:
        valueFiles:
          - $values/kubernetes/overrides/cloudflare-ddns/values.yaml
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
