all:
  vars:
    ansible_user: cloud-user
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=accept-new
      -o ConnectTimeout=15
      -o BatchMode=yes
    ansible_pull_repo: "https://github.com/InputObject2/homelab.git"
    ansible_pull_playbook: "infrastructure/domain-controllers/ansible/site.yml"
    ansible_pull_inventory: "infrastructure/domain-controllers/ansible/inventory/hosts.yml"
    dns_forwarder_ips: "10.222.0.186 10.222.0.187"
    beyla_otlp_endpoint: "http://10.222.0.187:4318"
  children:
    domain_controllers:
      hosts:
        us20-dc-63165:
          ansible_host: 10.222.0.18
        us20-dc-97332:
          ansible_host: 10.222.0.19
