# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    type: deployment
    strategy: RollingUpdate
    replicas: 1
    annotations:
      k8s_image_swapper: disabled
    containers:
      main:
        image:
          repository: searxng/searxng
          tag: 2026.3.6-0716de6bc
        env:
          - name: SEARXNG_BASE_URL
            value: "http://localhost:8080/"
          - name: SEARXNG_BIND_ADDRESS
            value: "0.0.0.0:8080"
          - name: SEARXNG_INSTANCE_NAME
            value: "Main Cluster Internal SearXNG"
          - name: SEARXNG_SETTINGS_PATH
            value: "/etc/searxng/settings.yml"
          - name: CONFIG_PATH
            value: "/usr/local/searxng/searx"
          - name: SEARXNG_SECRET
            valueFrom:
              secretKeyRef:
                name: searxng-secret
                key: secret_key

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: false

configMaps:
  searxng:
    enabled: true
    suffix: config
    data:
      settings.yml: |
        use_default_settings: true
        search:
          formats:
            - html
            - json
        language: en
        locale: en
persistence:
  config:
    enabled: true
    type: configMap
    name: searxng-config
    advancedMounts:
      main:
        main:
          - path: /etc/searxng/

rawResources:
  external-secret:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    spec:
      metadata:
        name: searxng-secret
      spec:
        data:
          - remoteRef:
              conversionStrategy: Default
              decodingStrategy: None
              key: apps/searxng/secret
              metadataPolicy: None
              property: secret_key
            secretKey: secret_key
        refreshInterval: 1h0m0s
        secretStoreRef:
          kind: ClusterSecretStore
          name: vault-backend
        target:
          creationPolicy: Owner
          deletionPolicy: Retain
          name: searxng-secret
