version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.10.0@sha256:4a61322ac1103a0e3aea2a61ef1718422a48fa046441f299d71e660a3bc71ae9
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090/tcp"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:12.4.2@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - /opt/secrets/observability/observability.env

  loki:
    image: grafana/loki:3.7.1@sha256:73e905b51a7f917f7a1075e4be68759df30226e03dcb3cd2213b989cc0dc8eb4
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100/tcp"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki

  influxdb:
    image: influxdb:2.8.0@sha256:71f2bce68b47a3e26c1ed38f7480a9372b008ba9b7c8a35cb2c913d3102d377f
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086/tcp"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    env_file:
      - /opt/secrets/observability/observability.env

  promtail:
    image: grafana/promtail:3.6.10@sha256:2a0f5e3e160ee5d549c585f6cc4f4e1c566ff783324a424bd75bc16503fc660e
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command:
      - '-config.file=/etc/promtail/config.yaml'

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  influxdb_data:
