global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node
    static_configs:
      - targets:
          # using abridged names since the dns will auto-complete the rest
          # physical hosts
          - srv-16-backups.core:9100
          - srv-18-truenas.core:9100
          - srv-26.core:9100
          - srv-27.core:9100
          - srv-28.core:9100

          # virtual machines
          - us20-dc-63165.core:9100 # ad
          - us20-dc-97332.core:9100 # ad
          - us20-voip-2218.core:9100 # voip
          - us20-matterbridge-6960.wifi:9100 # home-assistant matter bridge
          - us20-gateway-3714.core:9100 # tailnet subnet router (tailscale)

          # Kubernetes prometheus instance
          - prometheus:9100

  - job_name: dc-samba-ad-exporter
    scrape_interval: 30s
    static_configs:
      - targets:
          - us20-dc-63165.core:9101
          - us20-dc-97332.core:9101
        labels:
          group: domain_controllers

  - job_name: tempo
    scrape_interval: 30s
    static_configs:
      - targets:
          - tempo:3200
        labels:
          service: tempo

  - job_name: xenserver
    scrape_interval: 60s
    scrape_timeout: 50s
    static_configs:
      - targets:
          - xcp-ng:9100 # the xen-exporter container, which scrapes the XCP-ng host and exposes pool metrics on port 9100
