global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node
    static_configs:
      - targets:
          # physical hosts
          - 10.222.0.176:9100
          - 10.222.0.177:9100
          - 10.222.0.178:9100
          - 10.222.0.186:9100
          - 10.222.0.187:9100

          # virtual machines
          - 10.222.0.18:9100 # ad
          - 10.222.0.19:9100 # ad
          - 10.222.0.30:9100 # voip
          - 10.222.30.228:9100 # home-assistant matter bridge
          - 10.99.99.101:9100 # tailnet subnet router (tailscale)

          # Kubernetes prometheus instance
          - prometheus:9100

  - job_name: dc-samba-ad-exporter
    scrape_interval: 30s
    static_configs:
      - targets:
          - 10.222.0.18:9101
          - 10.222.0.19:9101
        labels:
          group: domain_controllers

  - job_name: tempo
    scrape_interval: 30s
    static_configs:
      - targets:
          - tempo:3200
        labels:
          service: tempo

  - job_name: xenserver
    scrape_interval: 60s
    scrape_timeout: 50s
    static_configs:
      - targets:
          - xcp-ng-exporter:9100 # the xen-exporter container, which scrapes the XCP-ng host and exposes pool metrics on port 9100
