apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-private-registry
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      targetRevision: 4.1.2
      helm:
        valueFiles:
          - $values/kubernetes/overrides/docker-private-registry/values.yaml
        parameters:
          - name: 'ingress.main.annotations.external-dns\.alpha\.kubernetes\.io/hostname'
            value: '{{ .Values.dockerPrivateRegistry.hostname }}.'
          - name: 'ingress.main.hosts[0].host'
            value: {{ .Values.dockerPrivateRegistry.hostname | quote }}
          - name: 'ingress.main.tls[0].hosts[0]'
            value: {{ .Values.dockerPrivateRegistry.hostname | quote }}
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: docker-private-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
