apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller-public
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: nginx-ingress-controller
      targetRevision: 11.6.12
      helm:
        valueFiles:
          - $values/kubernetes/overrides/ingress-public/values.yaml
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
