version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:2.334.0@sha256:da8f1a351d2b93ee74602154545d2954c31225dfb730265f87079ed9884fc7ea
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/home/runner
    env_file:
      - /opt/secrets/github-runner/github-runner.env

volumes:
  runner_data:
