version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:2.333.1@sha256:07aa22ebda2133771e08c4a2b5b879927d49c1d3c61a3ceaddf72c92e099d429
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/home/runner
    env_file:
      - /opt/secrets/github-runner/github-runner.env

volumes:
  runner_data: