version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:2.336.0@sha256:fc28f4cd67cacf3024984d873b2adbbd5809b85095747fa3fcd2421c098fb846
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/home/runner
    env_file:
      - /opt/secrets/github-runner/github-runner.env

volumes:
  runner_data:
