- name: restart samba-ad-dc
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: restarted

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: restart rsync
  ansible.builtin.systemd:
    name: rsync
    state: restarted
