---
# Install Docker and Docker Compose

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.asc

- name: Set permissions on Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu plucky stable"
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: cloud-user
    groups: docker
    append: yes

- name: Enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Create base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/secrets
    - /opt/vault-agent
    - /opt/stacks
