{{- if .Values.stacks.media.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-stack
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision }}
    path: kubernetes/stacks/media
    helm:
      parameters:
        - name: domain
          value: {{ .Values.domain | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}