ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  # @section -- External Tools configuration
  enabled: false

ollamaUrls:
 - http://ollama.ollama.svc.cluster.local:11434


image:
  tag: v0.8.9

ingress:
  enabled: true
  class: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-dns01
    external-dns.alpha.kubernetes.io/hostname: chat.example.com.
  host: "chat.example.com"
  tls: true

persistence:
  enabled: true
  size: 50Gi
  accessModes:
    - ReadWriteMany
  storageClass: "truenas-nfs-nas"

pipelines:
  persistence:
    enabled: true
    size: 50Gi
    accessModes:
      - ReadWriteMany
    storageClass: "truenas-nfs-nas"

extraEnvVars:
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: open-webui-oidc-creds
        key: client_id
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: open-webui-oidc-creds
        key: client_secret
  - name: OPENID_PROVIDER_URL
    valueFrom:
      secretKeyRef:
        name: open-webui-oidc-creds
        key: issuer_url
  - name: OAUTH_PROVIDER_NAME
    valueFrom:
      secretKeyRef:
        name: open-webui-oidc-creds
        key: provider_name
  - name: OPENID_REDIRECT_URI
    valueFrom:
      secretKeyRef:
        name: open-webui-oidc-creds
        key: redirect_uri
  - name: ENABLE_OAUTH_SIGNUP
    value: "true"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "true"
  - name: ENABLE_LOGIN_FORM
    value: "false"
  - name: OAUTH_SCOPES
    value: "openid email profile"
  - name: ENABLE_RAG_WEB_SEARCH
    value: "true"
  - name: RAG_WEB_SEARCH_ENGINE
    value: "searxng"
  - name: SEARXNG_QUERY_URL
    value: "http://searxng.ollama.svc.cluster.local:8080/search?q=<query>&format=json"

extraResources:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: open-webui-oidc-creds
    spec:
      data:
        - remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: apps/open-webui/oidc
            metadataPolicy: None
            property: client_id
          secretKey: client_id
        - remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: apps/open-webui/oidc
            metadataPolicy: None
            property: client_secret
          secretKey: client_secret
        - remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: apps/open-webui/oidc
            metadataPolicy: None
            property: issuer_url
          secretKey: issuer_url
        - remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: apps/open-webui/oidc
            metadataPolicy: None
            property: provider_name
          secretKey: provider_name
        - remoteRef:
            conversionStrategy: Default
            decodingStrategy: None
            key: apps/open-webui/oidc
            metadataPolicy: None
            property: redirect_uri
          secretKey: redirect_uri
      refreshInterval: 1h0m0s
      secretStoreRef:
        kind: ClusterSecretStore
        name: vault-backend
      target:
        creationPolicy: Owner
        deletionPolicy: Retain
        name: open-webui-oidc-creds